### PR TITLE
Replace require with ESM dynamic import and added a secound example

### PR DESCRIPTION
**Pull request by reinerBa**
The last Pull request screwed it again. Because of that I wrote a secound example app to test the library.
Please check if the 'file://' string in line [203](https://github.com/reinerBa/vite-plugin-mock-server/blob/patch-3/src/index.ts#L213) is a problem for non-windows os, for windows it was necessary.

I changed the build-script to be os agnostic. I further changed the readme, because ´req.body` was no longer working.

### CODE REVIEW

**Comment by steveworkman** [comment]
+1 to this change, because this plugin no longer works in non-ESM mode it's breaking on `require.cache`

Alternatively, building it as both CJS and ESM would make it backward-compatible with vite 4.x and below.

**Comment by reinerBa** [comment]
I added a github action. It restores the dependencies and builds the plugin and example2. 
After that it starts the vite development server of example2 and therminates it after 5 secounds. The last two errors were runtime errors and discovered only at runtime. In case of another runtime error, I think the CI will fail.
The CI runs on the latest windows and linux os and on the last three node-versions. 

grafik

The npm publish could be added in a github action as well.

**Comment by reinerBa** [comment]
The plugin doesn't works, I will add an api-test after fixing.

**Comment by reinerBa** [comment]
I added api-tests for both examples.

**Comment by 1revolman1** [comment]
+1 to this change

**Comment by briandelancey** [comment]
Any word on this @reinerBa ?

**Comment by ryandoll** [comment]
Can this get reviewed please, @reinerBa ?

**Comment by reinerBa** [comment]
I have no edit-rights here. I pushed merge requests to solve the issues but the last one was not confirmes. Therfore i published my changes and a changed api as a fork https://github.com/reinerBa/vite-plugin-mock-simple

**Comment by ryandoll** [comment]
@octoape do you have write access to merge this in?

**Comment by octoape** [comment]
PR https://github.com/enjoycoding/vite-plugin-mock-server/pull/29 has been merged, thank you for @reinerBa contribution.

**Pull request merged**
